# Site settings
title: SimpleSAMLphp
email: support@feide.no
description: SimpleSAMLphp** is an award-winning application written in native PHP that deals with authentication. It
  implements support for multiple protocols, most notably SAML, OpenID or OAuth.
baseurl: ""
url: "https://simplesamlphp.github.io"
twitter_username: simplesamlphp
github_username:  simplesamlphp

# Build settings
markdown: kramdown
